site_name:  seq2seq
theme: readthedocs
extra_css: [extra.css]
pages:
    - Overview: index.md
    - Getting Started: getting_started.md
    - Data: data.md
    - Models: models.md
    - Training: training.md
    - Inference: inference.md
    - Tools: tools.md
    - Results and Pre-Trained Models: benchmarks.md
    - Developer Guide: developer_guide.md