site_name:  seq2seq
theme: readthedocs
extra_css: [extra.css]
pages:
    - Overview: index.md
    - Getting Started: getting_started.md
    - Data: data.md
    - Training: training.md
    - Inference: inference.md
    - Model Reference: models.md
    - Encoder Reference: encoders.md
    - Decoder Reference: decoders.md
    - Tools: tools.md
    - Benchmarks: benchmarks.md
    - Contributing: contributing.md