site_name:  seq2seq
theme: readthedocs
pages:
    - Overview: overview.md
    - Getting Started: getting_started.md
    - Data: data.md
    - Models: models.md
    - Training: training.md
    - Inference: inference.md
    - Benchmarks: benchmarks.md
    - Profiling: profiling.md
    - Developer Guide: developer_guide.md